-- ===================================================
--  MIGRACIÓN: INDICADORES PEPSICO
--  DESCRIPCIÓN: Campos adicionales y nuevas tablas para el módulo de indicadores
--  FECHA: 2026-04-20
-- ===================================================

-- USE RENOA_PEPSICO; -- Eliminado para que el motor decida o se use la conexión actual
 
-- Agregar campos adicionales al catálogo de puestos existente
ALTER TABLE PSC_PUESTO ADD COLUMN PU_MODALIDAD VARCHAR(100);

-- 2) TABLA DE CARGOS DE PERSONAL (CATÁLOGO)
CREATE TABLE IF NOT EXISTS PSC_CARGO_PERSONAL (
    CP_IDCARGO_PK       INT             AUTO_INCREMENT PRIMARY KEY,
    CP_NOMBRE           VARCHAR(100)    NOT NULL UNIQUE,
    CP_ACTIVO           VARCHAR(2)      DEFAULT 'SI' NOT NULL,
    CP_CREADOPOR        VARCHAR(100)    DEFAULT 'SISTEMA',
    CP_CREADOEN         DATETIME        DEFAULT CURRENT_TIMESTAMP
);

-- Insertar cargos base
INSERT IGNORE INTO PSC_CARGO_PERSONAL (CP_NOMBRE) VALUES 
('ADMINISTRADOR'), 
('GUARDA DE SEGURIDAD'), 
('OPERADOR DE MEDIOS'), 
('SUPERVISOR');

-- 3) TABLA DE PERSONAL / COLABORADORES
CREATE TABLE IF NOT EXISTS PSC_PERSONAL (
    PR_IDPERSONAL_PK    INT             AUTO_INCREMENT PRIMARY KEY,
    CP_IDCARGO_FK       INT             NOT NULL,
    SE_IDSEDE_FK        INT             NULL,     -- Sede asignada (para Supervisores/Ops)
    PU_IDPUESTO_FK      INT             NULL,     -- Puesto asignado (para Guardas)
    PR_NOMBRE           VARCHAR(150),
    PR_FOTO_URL         VARCHAR(500),
    PR_CARGO_LARGO      VARCHAR(255)    NOT NULL, -- Ej: Supervisor Planta Alimentos Funza
    PR_GENERO           VARCHAR(20)     NOT NULL, -- HOMBRE, MUJER
    PR_ACTIVO           VARCHAR(2)      DEFAULT 'SI' NOT NULL,
    PR_CREADOPOR        VARCHAR(100)    DEFAULT 'SISTEMA',
    PR_CREADOEN         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    PR_IDJEFE_FK        INT             NULL,     -- Jefe directo (para Organigrama)
    FOREIGN KEY (CP_IDCARGO_FK) REFERENCES PSC_CARGO_PERSONAL(CP_IDCARGO_PK),
    FOREIGN KEY (SE_IDSEDE_FK) REFERENCES PSC_SEDE(SE_IDSEDE_PK),
    FOREIGN KEY (PU_IDPUESTO_FK) REFERENCES PSC_PUESTO(PU_IDPUESTO_PK),
    FOREIGN KEY (PR_IDJEFE_FK) REFERENCES PSC_PERSONAL(PR_IDPERSONAL_PK),
    CHECK (PR_GENERO IN ('HOMBRE', 'MUJER')),
    CHECK (PR_ACTIVO IN ('SI', 'NO'))
);

-- 4) GESTIÓN DE VISITAS
CREATE TABLE IF NOT EXISTS PSC_VISITA (
    VI_IDVISITA_PK      INT             AUTO_INCREMENT PRIMARY KEY,
    PR_IDPERSONAL_FK    INT             NOT NULL,
    SE_IDSEDE_FK        INT             NOT NULL,
    VI_FECHA_INICIO     DATETIME        NOT NULL,
    VI_FECHA_FIN        DATETIME,
    VI_ESTADO           VARCHAR(20)     DEFAULT 'EN CURSO',
    VI_COMENTARIOS      LONGTEXT,
    FOREIGN KEY (PR_IDPERSONAL_FK) REFERENCES PSC_PERSONAL(PR_IDPERSONAL_PK)
);

-- 5) TABLA DE ROTACIÓN DE PERSONAL
CREATE TABLE IF NOT EXISTS PSC_ROTACION (
    RO_IDROTACION_PK    INT             AUTO_INCREMENT PRIMARY KEY,
    PR_IDPERSONAL_FK    INT             NOT NULL,
    RO_TIPO             VARCHAR(50)     NOT NULL, -- RENUNCIA, DESPIDO
    RO_FECHA            DATE            NOT NULL,
    RO_MOTIVO           LONGTEXT,
    FOREIGN KEY (PR_IDPERSONAL_FK) REFERENCES PSC_PERSONAL(PR_IDPERSONAL_PK)
);
