-- MIGRACIÓN FINAL PARA EL MÓDULO DE GESTIÓN DE VISITAS (CRONOGRAMA)
-- FECHA: 2026-04-22
-- SOLUCIÓN: Limpieza total sin campos de ciudad innecesarios

SET FOREIGN_KEY_CHECKS = 0;

USE RENOA_PEPSICO;

-- Limpieza agresiva de todas las posibles tablas antiguas
DROP TABLE IF EXISTS PSC_VISITA_IMAGEN;
DROP TABLE IF EXISTS PSC_VISITA_RESULTADO;
DROP TABLE IF EXISTS PSC_VISITA_DETALLE;
DROP TABLE IF EXISTS PSC_VISITA;
DROP TABLE IF EXISTS PSC_VISITA_TAREA;

SET FOREIGN_KEY_CHECKS = 1;

-- 1. Catálogo de Tareas
CREATE TABLE IF NOT EXISTS PSC_VISITA_TAREA (
    VT_IDTAREA_PK INT AUTO_INCREMENT PRIMARY KEY,
    VT_NOMBRE VARCHAR(255) NOT NULL,
    VT_DESCRIPCION TEXT,
    VT_ACTIVO VARCHAR(2) DEFAULT 'SI',
    VT_CREADOPOR VARCHAR(100) DEFAULT 'SISTEMA',
    VT_CREADOEN DATETIME DEFAULT CURRENT_TIMESTAMP,
    VT_MODIFICPOR VARCHAR(100),
    VT_MODIFICEN DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 2. Tabla de Planeación y Ejecución de Visitas
CREATE TABLE IF NOT EXISTS PSC_VISITA (
    VI_IDVISITA_PK INT AUTO_INCREMENT PRIMARY KEY,
    SE_IDSEDE_FK INT NOT NULL,
    VI_FECHA_PLANEADA DATE NOT NULL,
    VI_ESTADO VARCHAR(20) DEFAULT 'PLANEADA',
    VI_FECHA_EJECUCION DATETIME NULL,
    VI_RESPONSABLE_EJECUCION VARCHAR(100),
    VI_OBSERVACIONES LONGTEXT,
    VI_ACTIVO VARCHAR(2) DEFAULT 'SI',
    VI_CREADOPOR VARCHAR(100) DEFAULT 'SISTEMA',
    VI_CREADOEN DATETIME DEFAULT CURRENT_TIMESTAMP,
    VI_MODIFICPOR VARCHAR(100),
    VI_MODIFICEN DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SE_IDSEDE_FK) REFERENCES PSC_SEDE(SE_IDSEDE_PK)
);

-- 3. Tabla de Detalles de Visita (Tareas Registradas)
CREATE TABLE IF NOT EXISTS PSC_VISITA_DETALLE (
    VD_IDDETALLE_PK INT AUTO_INCREMENT PRIMARY KEY,
    VI_IDVISITA_FK INT NOT NULL,
    VT_IDTAREA_FK INT NOT NULL,
    VD_HALLAZGO TEXT,
    VD_CREADOEN DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VI_IDVISITA_FK) REFERENCES PSC_VISITA(VI_IDVISITA_PK) ON DELETE CASCADE,
    FOREIGN KEY (VT_IDTAREA_FK) REFERENCES PSC_VISITA_TAREA(VT_IDTAREA_PK)
);

-- 4. Tabla de Evidencias Fotográficas
CREATE TABLE IF NOT EXISTS PSC_VISITA_IMAGEN (
    VIM_IDIMAGEN_PK INT AUTO_INCREMENT PRIMARY KEY,
    VD_IDDETALLE_FK INT NOT NULL,
    VIM_URL VARCHAR(500) NOT NULL,
    VIM_CREADOEN DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VD_IDDETALLE_FK) REFERENCES PSC_VISITA_DETALLE(VD_IDDETALLE_PK) ON DELETE CASCADE
);

-- 5. Índices para optimización
CREATE INDEX IDX_VISITA_FECHA ON PSC_VISITA(VI_FECHA_PLANEADA);
CREATE INDEX IDX_VISITA_SEDE ON PSC_VISITA(SE_IDSEDE_FK);

-- 6. Data Inicial
INSERT INTO PSC_VISITA_TAREA (VT_NOMBRE) VALUES 
('Verificación de Equipos Control de Acceso'),
('Revisión de Bitácoras de Seguridad'),
('Inspección de Perímetros y Cercas'),
('Prueba de Sistema de Intrusión (Sensores)'),
('Verificación de Alumbrado Táctico'),
('Entrevista con personal de turno');
